### ISSUE TITLE
Alert / Notify for incoming call when app is closed

### ISSUE THREAD

**Issue by Adeel984** [flutter-webrtc/flutter-webrtc-demo#112]
How can we implement call ringing to display if someone is calling and app is closed?
Please help in this regards.

**Comment by ycherniavskyi** [comment]
On mobile, this can be achieved with Push Notification ([PushKit](https://developer.apple.com/documentation/pushkit) for iOS and regular Notifications maybe with high priority for Android.

**Comment by Adeel984** [comment]
I've heard about `ConnectionService` on Android & `CallKit` on iOS. Should i implement that as Whatsapp may be use the same.
