### ISSUE TITLE
> > Hey, did you make the video full screen?

### ISSUE THREAD

**Issue by LucasFancation** [flutter-webrtc/flutter-webrtc-demo#114]
> > Hey, did you make the video full screen?
> 
> After reading the code in RTCVideoRenderer
> you can try this, it worked for me
> _remoteRenderer.objectFit = RTCVideoViewObjectFit.RTCVideoViewObjectFitCover;

Hi, this code is no longer being available, so any suggestions on working on the fullscreen? Thanks

**Comment by lannes** [comment]
RTCVideoView(_remoteRenderer,
                      objectFit:
                          RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)

> > > Hey, did you make the video full screen?
> > 
> > 
> > After reading the code in RTCVideoRenderer
> > you can try this, it worked for me
> > _remoteRenderer.objectFit = RTCVideoViewObjectFit.RTCVideoViewObjectFitCover;
> 
> Hi, this code is no longer being available, so any suggestions on working on the fullscreen? Thanks

Here you are
RTCVideoView(_remoteRenderer, objectFit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)
