### ISSUE TITLE
P2P call sample: remote peer video is blank

### ISSUE THREAD

**Issue by ganeshub** [flutter-webrtc/flutter-webrtc-demo#118]
In P2P call local stream renders but remote render as grey.
How to fix this ?

**Comment by ganeshub** [comment]
Found similar question

**Comment by ganeshub** [comment]
Tried solution given in https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/88
Used real devices instead of emulators but still _remoteRender is just blank or grey

**Comment by ganeshub** [comment]
@ycherniavskyi @CoreyCole @vasopikof @LinusU help

**Comment by s7070099** [comment]
Use **setState(() { });** to set srcObject of RTCVideoRenderer

`_signaling.onAddRemoteStream = ((_, stream, role) {
        print(_net.user.registerCode + ' onAddRemoteStream ' + role);
        print(' stream.id ' + stream.id.toString());

        setState(() {
          if (role == "USER") _userRenderer.srcObject = stream;
          if (role == "STAFF") _staffRenderer.srcObject = stream;
          if (role == "AMBULANCE") _ambulanceRenderer.srcObject = stream;
        });
      });`

**Comment by ganeshub** [comment]
Thanks @s7070099, Added setState() but now i get black square instead grey so still not working.

**Comment by dynaevdv** [comment]
> Thanks @s7070099, Added setState() but now i get black square instead grey so still not working.

 _signaling.onLocalStream = ((_, stream) {
        _localRenderer.srcObject = stream;

        setState(() {});
      });

      _signaling.onAddRemoteStream = ((_, stream) {
        _remoteRenderer.srcObject = stream;

        setState(() {});
      });
      
     Is enough for fix grey screen issue

**Comment by myusuf17** [comment]
maybe i have different problem
when running sample
i cant get list i dont know why maybe because this

fyi already using web and work

![image](https://user-images.githubusercontent.com/5269806/114840801-5ef1e880-9e01-11eb-816c-a3e50338b4eb.png)

**Comment by chhota89** [comment]
Any solution for gray screen issue?

**Comment by mayaparamita** [comment]
> ```
>        _localRenderer.srcObject = stream;
> 
>        setState(() {}); // ADD THIS
>      });
> 
>      _signaling.onAddRemoteStream = ((_, stream) {
>        _remoteRenderer.srcObject = stream;
> 
>        setState(() {}); // AND ADD THIS
>      });
> ```
> 
> Is enough for fix grey screen issue

It WORKS! Thanks very much! 😁

**Comment by Shanki070** [comment]
> ```
>        _localRenderer.srcObject = stream;
> 
>        setState(() {}); // ADD THIS
>      });
> 
>      _signaling.onAddRemoteStream = ((_, stream) {
>        _remoteRenderer.srcObject = stream;
> 
>        setState(() {}); // AND ADD THIS
>      });
> ```
> 
> 
>      
>   
> 
> Is enough for fix grey screen issue

this worked. Thanks.

**Comment by mrhaydari** [comment]
for me the problem is true value in _invitePeer function, true is screen sharing and false is a camera, and I don't check this value and screen sharing don't work for me and I don't see any permission error, That's why the screen was completely black

**Comment by ggdream** [comment]
https://github.com/flutter-webrtc/flutter-webrtc-server/blob/2b074d179507197307127b65270c1e1286de192d/pkg/turn/turn.go#L19

I encountered and solved the problem that the remote video is not displayed, but this solution is only for the problem caused by the use of `dome.cloudwebrtc.com`. This is just because the turn service of the `dome.cloudwebrtc.com` server source code is set to a local loopback instead of public network exposure.
