### ISSUE TITLE
switchCamera not working on web

### ISSUE THREAD

**Issue by define111** [flutter-webrtc/flutter-webrtc-demo#123]
So the method _switchCamera()_ from _Signalling.dart_ is working on Android. But is failing on web, could somebody confirm this? I test with chrome and edge.
To fix this I have investigated with facingMode like described here: https://gosink.in/webrtc-switch-cameras-using-javascript-getusermedia/ ,but I stumbled on the mediaConstraints, because the field facingMode is set to false after calling _var stream = await navigator.mediaDevices.getUserMedia(mediaConstraints)_ if I understand correctly.
Before I investigate further please confirm if the method _switchCamera()_ should be working on web as in the flutter webrtc demo or is it not supported for web yet?

Just in case somebody is interested I tried this:
```
import 'package:flutter/foundation.dart' show kIsWeb;

Future<void> switchCamera() async {
    if (_localStream != null) {
      if (kIsWeb) {
        _localStream.getTracks().forEach((element) async {
          await element.stop();
        });
        await _localStream.dispose();
        _localStream = null;
        if (mediaConstraints['video']['facingMode']=='user') {
          mediaConstraints['video']['facingMode'] = 'environment';
        } else {
          mediaConstraints['video']['facingMode']= 'user';
        };
        _localStream = await createStream();
        var stream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
        onLocalStream?.call(null, stream);
      } else {
        await Helper.switchCamera(_localStream.getVideoTracks()[0]);
      }
    }
  }
```
But _(mediaConstraints['video']['facingMode']_ does not exist at this stage.

**Comment by define111** [comment]
Ok. I actually got the method _switchCamera()_ working locally by calling it like this in web:
`  Future<void> switchCameraWeb() async {
    if (_localStream != null) {
      var actualDevice = _localStream.getTracks();
      var deviceID;
      print('actualdevice: ${actualDevice[1].label}');
      await navigator.mediaDevices.enumerateDevices().then((devices) {
        devices.forEach((device) {
          if (device.kind == 'videoinput' &&
              device.label != actualDevice[1].label) {
            deviceID = device.deviceId;
            return;
          }
        });
      });
      print('deviceID: $deviceID');
      await Helper.switchCamera(
          _localStream.getVideoTracks()[0], deviceID, _localStream);
}`
However the stream is not getting updated for the other peer. I will work on this.

**Comment by Gene-Dana** [comment]
I'm not getting it to work on web whatsoever ! Every time I run an example, the browser closes after accepting permission

**Comment by Gene-Dana** [comment]
Do I have to run a signaling server perhaps?

**Comment by define111** [comment]
No answer? Wow!
