### ISSUE TITLE
Play remote Audio

### ISSUE THREAD

**Issue by AniketBhadane** [flutter-webrtc/flutter-webrtc-demo#126]
I wish to play audio from remote stream of webrtc connection, in Flutter. The examples of flutter webrtc use `RTCVideoRenderer`, but there is no video in my case. The remote stream only consists of audio.

In short:

    pc.onTrack = (event) {
      // how can I play the Audio stream in event.streams[0] ?
    };

Code:

    MediaStream _localStream = await createStream();
    RTCPeerConnection pc = await createPeerConnection({});
    
    _localStream.getTracks().forEach((track) async => await pc.addTrack(track, _localStream));	
    
    pc.onTrack = (event) {
      // how can I play the Audio stream in event.streams[0] ?
    };
    	
    Future<MediaStream> createStream() async {
      final Map<String, dynamic> mediaConstraints = {
        'audio': true,
        'video': false
      };
    
      MediaStream stream = await MediaDevices.getUserMedia(mediaConstraints);
      return stream;
    }

How can I play the audio from remote stream in flutter?

**Comment by nanthakumarg** [comment]
Same RTCVideoRenderer can be used for audio also. Actullay RTCVideoView is used for displaying video.  Since video is not requested RTCVideoRenderer is able to play audio.

**Comment by supermuesli** [comment]
I am facing a similar problem. Weirdly, in my case I completely deleted the RTCVideoRenderer and set the getUserMedia constraints to audio-only, however when testing the demo on an Android Phone and a Chrome Browser, the Android Phone still  outputs audio while the Browser doesn't. 
Why is my phone playing audio when I have not implemented an audio player in the demo? I can't seem to trace the audio back to the corresponding codesnippet in the demo.
my ```Signaling._remoteStreams``` is not being used anywhere in the demo !

**Comment by BradenBagby** [comment]
I am also trying to figure out why my webrtc immediately begins playing audio on successful connection. I do not have any RTCVideoRenderer. @supermuesli

**Comment by wupengbigMarker** [comment]
@BradenBagby hi, did you know how to solve this issue

**Comment by wupengbigMarker** [comment]
> I am facing a similar problem. Weirdly, in my case I completely deleted the RTCVideoRenderer and set the getUserMedia constraints to audio-only, however when testing the demo on an Android Phone and a Chrome Browser, the Android Phone still outputs audio while the Browser doesn't.
> Why is my phone playing audio when I have not implemented an audio player in the demo? I can't seem to trace the audio back to the corresponding codesnippet in the demo.
> my `Signaling._remoteStreams` is not being used anywhere in the demo !

How did u solve this in the end
