### ISSUE TITLE
failing to get any audio or video on screen

### ISSUE THREAD

**Issue by gc-robotics** [flutter-webrtc/flutter-webrtc-demo#136]
Hi there, 

I am using flutter-webrtc-server with two clients: one is flutter-webrtc-demo and the other one is a python bespoke client. 
I have implemented the full webrtc flow on the python client. It connects to the server, informs about its presence (PEERS), it is capable to creating an ANSWER to respond an offer; I can also see that it performs ICE exchanging. 

flutter-webrtc-demo connects and switches to the "call screen", showing two video stream "boxes". However, there is no image/video or audio rendered. 

I get no errors on server, python client or flutter client. Could you please provide some suggestions/advises on how to debug this scenario pls? 

I am not an expert of WebRTC and I would appreciate some help. 

Thanks in advance.

**Comment by cloudwebrtc** [comment]
Can you provide some running logs? This will help me analyze the problem.
