### ISSUE TITLE
windows画面异常

### ISSUE THREAD

**Issue by dengwant** [flutter-webrtc/flutter-webrtc-demo#141]
在window上使用texture渲染视频帧，视频显示正常，会导致界面上其他UI比如文字、图标变成小方块，
下载demo，也会复现此问题，P2P Call Sample页面，鼠标悬浮左上角Back，会出现图标和文字变成小方块
希望帮助定位问题，涉及项目后续选型，非常感谢

**Comment by dengwant** [comment]
Using Texture to render a video frame in Window, the video will display properly, causing other UI elements on the screen such as text and icons to become small squares.

When you download the demo, this problem will also be repeated. The P2P Call Sample page, when the mouse hovers over the upper left corner Back btn, the icon and text will turn into small squares

Hope to help locate the problem, which involves the subsequent selection of the project. Thank you very much

**Comment by cloudwebrtc** [comment]
> 在window上使用texture渲染视频帧，视频显示正常，会导致界面上其他UI比如文字、图标变成小方块，
> 下载demo，也会复现此问题，P2P Call Sample页面，鼠标悬浮左上角Back，会出现图标和文字变成小方块
> 希望帮助定位问题，涉及项目后续选型，非常感谢

这应该是flutter engine for windows 的bug

**Comment by dengwant** [comment]
> > 在window上使用texture渲染视频帧，视频显示正常，会导致界面上其他UI比如文字、图标变成小方块，
> > 下载demo，也会复现此问题，P2P Call Sample页面，鼠标悬浮左上角Back，会出现图标和文字变成小方块
> > 希望帮助定位问题，涉及项目后续选型，非常感谢
> 
> 这应该是flutter engine for windows 的bug

了解 那应该是给flutter github下提issue了 这个问题对我们接入webrtc会有影响么

**Comment by dengwant** [comment]
flutter更新到dev-2.2.0-10.1.pre版本，UI显示正常，stable-2.0.5，UI还是异常
