### ISSUE TITLE
Unable to connect to demo-server in app

### ISSUE THREAD

**Issue by Pitazzo** [flutter-webrtc/flutter-webrtc-demo#16]
I've deployed the `flutter-webrtc-server` demo in my local network and it works fine while using it with my mobile browser (I'm able to call other users, etc). 
However, while using the _P2P Call Sample_ option in the demo Flutter app, when I tap "Connect" after introducing the address of the machine where the server has been deployed, nothing happens and the screen remains blank except for the blue navbar.

- I can't see any activity in the log of the server
- The app passes the basic API tests
- Android 9.0 on OnePlus5

Thanks in advance! I'm really interested in getting this to work!

**Comment by cloudwebrtc** [comment]
You can provide some logcat information.

**Comment by tonykawa** [comment]
I have this problem too.

**Comment by tonykawa** [comment]
Here is my logcat after input server ip and connect to server.

2019-03-25 15:54:04.007 6276-6276/com.cloudwebrtc.flutterwebrtcdemo I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
2019-03-25 15:54:04.100 6276-6276/com.cloudwebrtc.flutterwebrtcdemo I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
2019-03-25 15:54:04.192 6276-6276/com.cloudwebrtc.flutterwebrtcdemo I/zygote64: vendor::lge::hardware::configstore::V1_0::IConfigStore::getUBWCUsageFlag retrieved: 0 (default)
2019-03-25 15:54:04.195 6276-6276/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
2019-03-25 15:54:04.198 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: EglBase.create shared context
2019-03-25 15:54:04.198 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglBase14: SDK version: 26. isEGL14Supported: true
2019-03-25 15:54:04.405 6276-6276/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Initializing EglRenderer
2019-03-25 15:54:04.407 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: EglBase.create shared context
2019-03-25 15:54:04.408 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglBase14: SDK version: 26. isEGL14Supported: true
2019-03-25 15:54:08.232 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4026 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:08.434 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4022 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:12.259 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4027 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:12.460 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4025 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:16.287 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4027 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:16.487 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4027 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:20.314 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4026 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:20.514 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4027 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:24.336 6276-6435/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4022 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
2019-03-25 15:54:24.536 6276-6438/com.cloudwebrtc.flutterwebrtcdemo I/org.webrtc.Logging: EglRenderer: Duration: 4022 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by nhducseuit** [comment]
@tonykawa  Could you provide full working solution for this? I'm struggling with this too

**Comment by sabriismail4** [comment]
Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?

**Comment by jackChauT** [comment]
> @tonykawa & @nhducseuit Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?

Hi, The use case of @tonykawa is no network connection. If your use case is same, what you need to do is that let iceServers be empty array (i.e., 'iceServers': []) and server = 192.168.xx.xx (just the ip).

**Comment by sabriismail4** [comment]
> > @tonykawa & @nhducseuit Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?
> 
> Hi, The use case of @tonykawa is no Internet connection. If your use case is same, what you need to do is that let iceServers be empty array (i.e., 'iceServers': []) and server = 192.168.xx.xx (just the ip).

Well I need internet connection in my case, and I could not make the app work for P2P Call Connection from the emulator to the web app demo, which I've taken from https://github.com/cloudwebrtc/flutter-webrtc-server. I would really be thankful if you can help me with the issue. The message that I get continuously is (I/org.webrtc.Logging( 4222): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.), which I believe that it tells me it doesn't connect anywhere.

**Comment by jackChauT** [comment]
> > > @tonykawa & @nhducseuit Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?
> > 
> > 
> > Hi, The use case of @tonykawa is no Internet connection. If your use case is same, what you need to do is that let iceServers be empty array (i.e., 'iceServers': []) and server = 192.168.xx.xx (just the ip).
> 
> Well I need internet connection in my case, and I could not make the app work for P2P Call Connection from the emulator to the web app demo, which I've taken from https://github.com/cloudwebrtc/flutter-webrtc-server. I would really be thankful if you can help me with the issue. The message that I get continuously is (I/org.webrtc.Logging( 4222): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.), which I believe that it tells me it doesn't connect anywhere.

Have you updated your server ip? 
Please provide more error information.

**Comment by sabriismail4** [comment]
> > > > @tonykawa & @nhducseuit Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?
> > > 
> > > 
> > > Hi, The use case of @tonykawa is no Internet connection. If your use case is same, what you need to do is that let iceServers be empty array (i.e., 'iceServers': []) and server = 192.168.xx.xx (just the ip).
> > 
> > 
> > Well I need internet connection in my case, and I could not make the app work for P2P Call Connection from the emulator to the web app demo, which I've taken from https://github.com/cloudwebrtc/flutter-webrtc-server. I would really be thankful if you can help me with the issue. The message that I get continuously is (I/org.webrtc.Logging( 4222): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.), which I believe that it tells me it doesn't connect anywhere.
> 
> Have you updated your server ip?
> Please provide more error information.

By updating I am understanding to set it be equal to the ip that I want the app to load for me. If this is the correct way of updating that I understand, well I have updated the _serverAddress variable from the source code to be equal to the address "https://foo.com:8080". I haven't changed anything regarding iceServers[]. I would be very thankful if you can show with an example of all changes you do from the source code, how you update the server ip, which I believe is the serverIP variable from final String type.

**Comment by jackChauT** [comment]
> > > > > @tonykawa & @nhducseuit Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?
> > > > 
> > > > 
> > > > Hi, The use case of @tonykawa is no Internet connection. If your use case is same, what you need to do is that let iceServers be empty array (i.e., 'iceServers': []) and server = 192.168.xx.xx (just the ip).
> > > 
> > > 
> > > Well I need internet connection in my case, and I could not make the app work for P2P Call Connection from the emulator to the web app demo, which I've taken from https://github.com/cloudwebrtc/flutter-webrtc-server. I would really be thankful if you can help me with the issue. The message that I get continuously is (I/org.webrtc.Logging( 4222): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.), which I believe that it tells me it doesn't connect anywhere.
> > 
> > 
> > Have you updated your server ip?
> > Please provide more error information.
> 
> By updating I am understanding to set it be equal to the ip that I want the app to load for me. If this is the correct way of updating that I understand, well I have updated the _serverAddress variable from the source code to be equal to the address "https://foo.com:8080". I haven't changed anything regarding iceServers[]. I would be very thankful if you can show with an example of all changes you do from the source code, how you update the server ip, which I believe is the serverIP variable from final String type.
> Thanks in advance!

Please try to update the address from "https://foo.com:8080" to foo.com. Please make sure that foo.com is accessible.

**Comment by sabriismail4** [comment]
> oo.com. Please make sure that

Yes it is accessible

**Comment by Condelab** [comment]
@sabriismail4 i think its a permission issue if not then. 

> It seems it is somewhat stun/turn server problem. After configuration of real turn servers i found config which makes connection successful. If anyone has any related problem, visit http://numb.viagenie.ca create your turn server and edit signaling file (iceServers) with newly created info.

i got this [here ](https://github.com/cloudwebrtc/flutter-webrtc/issues/60)

**Comment by SkullEnemyX** [comment]
Even I am having the same issue where I used my laptop as the server and launched the webrtc server app. After then I launched the app on my device and entered the ip of my laptop but it is taking me to a screen where there is a blue appbar and nothing else. The whole screen is empty and I am pretty confused how to proceed. Can someone give me a detailed explaination on how to launch the app and the server if I am making a mistake. Urgent help required.

**Comment by Condelab** [comment]
@SkullEnemyX all you need do is to open the console of your browser through inspect tools, then you would see that your browser has blocked another port (bcos the app uses 2 ports - 4443 and 8086) so which ever one is blocked load it as a url on the same browser then the ssl error exception will ask you to create exception for the link, you click on proceed and thats all. by then the one user will be online which will be the browser. and if you want to connect another user, load the same url on another browser, that should give you another user.

**Comment by danielehrhardt** [comment]
```
I/flutter (28137): connect to wss://192.168.178.155:4443
E/flutter (28137): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'closeCode' was called on null.
E/flutter (28137): Receiver: null
E/flutter (28137): Tried calling: closeCode
E/flutter (28137): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (28137): #1      SimpleWebSocket.connect (package:flutter_webrtc_demo/src/utils/websocket.dart:29:28)
E/flutter (28137): <asynchronous suspension>
E/flutter (28137): #2      Signaling.connect (package:flutter_webrtc_demo/src/call_sample/signaling.dart:292:19)
E/flutter (28137): #3      _CallSampleState._connect (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:50:45)
E/flutter (28137): #4      _CallSampleState.initState (package:flutter_webrtc_demo/src/call_sample/call_sample.dart:32:5)
E/flutter (28137): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (28137): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (28137): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (28137): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (28137): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (28137): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (28137): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (28137): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (28137): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (28137): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (28137): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (28137): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (28137): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (28137): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (28137): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (28137): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (28137): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (28137): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (28137): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (28137): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (28137): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (28137): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (28137): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (28137): #44     ComponentElement.performRebuild (package:flutter/src/wi
```

**Comment by abheet-98** [comment]
> > > @tonykawa & @nhducseuit Can anyone tell me what exactly have you updated in the implementation with iceServers[] ?
> > 
> > 
> > Hi, The use case of @tonykawa is no Internet connection. If your use case is same, what you need to do is that let iceServers be empty array (i.e., 'iceServers': []) and server = 192.168.xx.xx (just the ip).
> 
> Well I need internet connection in my case, and I could not make the app work for P2P Call Connection from the emulator to the web app demo, which I've taken from https://github.com/cloudwebrtc/flutter-webrtc-server. I would really be thankful if you can help me with the issue. The message that I get continuously is (I/org.webrtc.Logging( 4222): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.), which I believe that it tells me it doesn't connect anywhere.

@sabriismail4 Ik its been a year since you were stuck with this issue.
Actually I have been stuck now with this issue.
Have you found the solution regarding this...getting an empty screen on the mobile device when pressed the P2P call sample button .
Thanks in advance !
