### ISSUE TITLE
Issues when call started from Androind device to Web service

### ISSUE THREAD

**Issue by robvr** [flutter-webrtc/flutter-webrtc-demo#166]
I'm facing issues establishing a video call between an Android device and the web service. The Android device and the web browser are both showing their local video correctly, but the remote video is not shown. This issue is faced only when the call is initiated from the Android device. The other way around, starting the call from the Web service works fine.
Checked issue 118 but it didn't help me. Also tried with working TURN servers.
Any help would be appreciated! Thanks!

**Comment by cloudwebrtc** [comment]
You have tried to rotate the phone screen after it is connected? This may be another rendering issue.

**Comment by robvr** [comment]
Let me check

**Comment by robvr** [comment]
Not working. Only a black screen showing.

**Comment by cloudwebrtc** [comment]
Please check the console log to see if there is an `
RTCIceConnectionStateConnected` message.
maybe it’s an `ice candidate` timing issue, I’m not sure

rob_ ***@***.***> 于2021年11月5日周五 下午11:08写道：

**Comment by robvr** [comment]
No I don't get this message `RTCIceConnectionStateConnected`

**Comment by cloudwebrtc** [comment]
It seems that the network layer is not connected, you should check the ice connectivity

**Comment by robvr** [comment]
Do you mean the TURN server? I don't get the `RTCIceConnectionStateConnected` message even when starting the call from the browser but the video streams in this case are shown correctly.

**Comment by cloudwebrtc** [comment]
You can add a log print here to know if ice is connected
https://github.com/flutter-webrtc/flutter-webrtc-demo/blob/master/lib/src/call_sample/signaling.dart#L410

**Comment by robvr** [comment]
I get this log when the call is started from the web browser:
```
I/flutter (23697): ****************
I/flutter (23697): RTCIceConnectionState.RTCIceConnectionStateConnected
I/flutter (23697): ****************
```

But when starting the call from an Android device towards the web browser, RTCIceConnectionState is stuck here:
```
I/flutter (23697): ****************
I/flutter (23697): RTCIceConnectionState.RTCIceConnectionStateChecking
I/flutter (23697): ****************
```

**Comment by robvr** [comment]
And after some seconds I got this:
```
I/flutter (23697): ****************
I/flutter (23697): RTCIceConnectionState.RTCIceConnectionStateFailed
I/flutter (23697): ****************
```

**Comment by robvr** [comment]
@cloudwebrtc Do you think I have an issue with the TURN server?

**Comment by robvr** [comment]
Sorry for wasting your time guys. Everything is working fine. My TURN server was having issues. Thanks for the support!

**Comment by Notebrains** [comment]
Do I have to create my own turn server to solve this issue?
