### ISSUE TITLE
Error While Running code

### ISSUE THREAD

**Issue by arun1989** [flutter-webrtc/flutter-webrtc-demo#194]
I am getting errors while compiling code. its from dependencies side aswell.

<img width="561" alt="Screenshot 2022-09-15 at 8 06 25 PM" src="https://user-images.githubusercontent.com/12507057/190529339-e83d6058-c42a-4d1b-8b87-14a99c717e51.png">

**Comment by chitraarasu** [comment]
I am also facing the same error

**Comment by chitraarasu** [comment]
After upgrading flutter_webrtc solved the problem.

**Comment by arun1989** [comment]
I just override dependency and it worked! 

dependency_overrides: 
    webrtc_interface: 1.0.2

**Comment by arun1989** [comment]
I just override dependency and it worked!

dependency_overrides:
webrtc_interface: 1.0.2
