### ISSUE TITLE
Error: The non-abstract class 'RTCVideoRenderer' ...

### ISSUE THREAD

**Issue by srlopez** [flutter-webrtc/flutter-webrtc-demo#195]
Hello,
Trying to launch the demo, on Windows 10, with Flutter 3.3 I get the following error message.

```
Error: The non-abstract class 'RTCVideoRenderer' is missing implementations for these members:
 -VideoRenderer.onFirstFrameRendered
```

I understand that the application is made in another version of Flutter.
Have you thought about upgrading the demo to 3.3?

Thank you

**Comment by chitraarasu** [comment]
I am also facing same issue

**Comment by timmy-gzw** [comment]
I am also facing same issue

**Comment by timmy-gzw** [comment]
> I am also facing same issue

After upgrading flutter_webrtc solved the problem.

**Comment by srlopez** [comment]
Thanks,
You are right. No issues after upgrade.
But I dont know how to setup  the demo. After start the server in my machine
```
go run cmd\server\main.go
2022-09-19T11:17:37+02:00 INF Flutter WebRTC Server listening on: 0.0.0.0:8086
```
Then start the demo width  `flutter run -d windows` , and setup the server `localhost:8086` ... dont know how to continue.

Thanks

**Comment by timmy-gzw** [comment]
> Thanks, You are right. No issues after upgrade. But I dont know how to setup the demo. After start the server in my machine
> 
> ```
> go run cmd\server\main.go
> 2022-09-19T11:17:37+02:00 INF Flutter WebRTC Server listening on: 0.0.0.0:8086
> ```
> 
> Then start the demo width `flutter run -d windows` , and setup the server `localhost:8086` ... dont know how to continue.
> 
> Thanks

Fill in 127.0.0.1 and fill in the ip address in another device.

**Comment by srlopez** [comment]
Thanks.
