### ISSUE TITLE
Registration with webrtc server? 

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/flutter-webrtc-demo#28]
Hi,

Is there anyway to call another p2p user without knowing their address? For example, one peer registers with the webrtc server and calls an alias and then the server returns the right address? Similar to a SIP registration?

Or is this just pure p2p? How do you recommend handling this list of online peers? 

Thanks.

**Comment by cloudwebrtc** [comment]
@ghenry There is a simple signaling server, similar to the sip registration and call process, through a random ID.

[flutter-webrtc-server](https://github.com/cloudwebrtc/flutter-webrtc-server)

Usually, webrtc needs a signaling server as the sdp and candidate exchange. I think pure p2p is not easy to implement. you may need a DHT stack to exchange SDP and candidate through DHT.

**Comment by ghenry** [comment]
On Sun, 11 Aug 2019, 04:09 CloudWebRTC, <notifications@github.com> wrote:

> @ghenry <https://github.com/ghenry> There is a simple signaling server,
> similar to the sip registration and call process, through a random ID.
>
> flutter-webrtc-server
> <https://github.com/cloudwebrtc/flutter-webrtc-server>
>

OK, thanks. I'm currently evaluatung the effort to use both with our own
SIP platform / custom setup versus writing dart-sip-ua and using that for
signalling with flutter-webrtc

Usually, webrtc needs a signaling server as the sdp and candidate exchange.
> I think pure p2p is not easy to implement. you may need a DHT stack to
> exchange SDP and candidate through DHT.
>

So bottom line is a server or muc is needed?

Thanks.

>

**Comment by ghenry** [comment]
There's also the javascript dart Bridge and the option to try JsSIP. I
wonder how that would go. Or using a java or kotlin sip plugin.

Have you done any work like this already?

Thanks.

**Comment by cloudwebrtc** [comment]
Developing a flutter plugin using the native sip stack can be costly, and developing on every platform [android/ios/desktop] would be terrible.
In fact, I prefer to port jssip to the dart version as a pure dart sip stack. I will create a dart sip repository so that more people can participate.

**Comment by ghenry** [comment]
That was my next idea; to port JsSIP to dart and call it `dart-sip-ua`, but I wanted to check everything you'd done first as that will be a big job too. I presume using it via dart JS loader would be a poor idea?

**Comment by cloudwebrtc** [comment]
> I presume using it via dart JS loader would be a poor idea?

I haven't test dart JS loader, so I don't know it. :(


> That was my next idea; to port JsSIP to dart and call it `dart-sip-ua`, but I wanted to check everything you'd done first as that will be a big job too.

Before I ported the [dart-sdp-transform](https://github.com/cloudwebrtc/dart-sdp-transform) from [clux/sdp-transform](https://github.com/clux/sdp-transform), the hardest part is the `grammar` parser, and the other is the conversion of asynchronous functions, use `Completer` to replace `Promise`, async/await, etc.


## I think the following parts should be done:

1, Necessary dependency package:
  We already have some dart package dependencies.
- [x] [flutter-webrtc](https://github.com/cloudwebrtc/flutter-webrtc)
- [x] [dart-events](https://github.com/cloudwebrtc/dart-events)
- [x] [dart-sdp-transform](https://github.com/cloudwebrtc/dart-sdp-transform)
- [ ] dart-debug? Maybe only needs a `logger.dart` to print logs?

2，Convert *.js to *.dart.
      during the time I saw `JsSIP` and `SIP.js`, it seems that `JsSIP` is easier to port.

3，Develop a beautiful sip client using Flutter.

**Comment by ghenry** [comment]
> > I presume using it via dart JS loader would be a poor idea?
> 
> I haven't test dart JS loader, so I don't know it. :(

OK, let's rule that out then.

> > That was my next idea; to port JsSIP to dart and call it `dart-sip-ua`, but I wanted to check everything you'd done first as that will be a big job too.
> 
> Before I ported the [dart-sdp-transform](https://github.com/cloudwebrtc/dart-sdp-transform) from [clux/sdp-transform](https://github.com/clux/sdp-transform), the hardest part is the `grammar` parser, and the other is the conversion of asynchronous functions, use `Completer` to replace `Promise`, async/await, etc.

So that's the SDP task solved already? Well, you need SDP for WebRTC anyway, so that must mean yes.

> ## I think the following parts should be done:
> 
> 1, Necessary dependency package:
> We already have some dart package dependencies.
> 
>     * [x]  [flutter-webrtc](https://github.com/cloudwebrtc/flutter-webrtc)
> 
>     * [x]  [dart-events](https://github.com/cloudwebrtc/dart-events)
> 
>     * [x]  [dart-sdp-transform](https://github.com/cloudwebrtc/dart-sdp-transform)
> 
>     * [ ]  dart-debug? Maybe only needs a `logger.dart` to print logs?
> 

Should `dart-sip-ua` be standalone or should it require flutter-webrtc? For my use-case I'd want all config to be able to be passed in as I plan to provision it via FCM data.

> 
> 2，Convert *.js to *.dart.
> during the time I saw `JsSIP` and `SIP.js`, it seems that `JsSIP` is easier to port.

Don't bother with SIP.js. JsSIP is older, more mature and proper. SIP.js is a fork form onSIP. 

> 3，Develop a beautiful sip client using Flutter.

A simple one, but with the option to be complicated :-)

**Comment by cloudwebrtc** [comment]
> Should `dart-sip-ua` be standalone or should it require flutter-webrtc?

If `dart-sip-ua` needs to be a client with audio/video, flutter-webrtc is necessary unless you want to use a different media engine, such as your own non-webrtc(For example, a media engine without ice/rtcp-fb.) media engine plugin, you need to wrap the sendOffer/sendAnswer/onOffer/onAnswer series of events and methods into an interface to dock your media engine.

> For my use-case I'd want all config to be able to be passed in as I plan to provision it via FCM data.

If you mean use FCM  data to configuration the sip account, audio/video codec order, I think it is possible. Take JsSIP as an example. When creating UA, a configuration parameter will be passed to the constructor.

```
// Create our JsSIP instance and run it:

Var socket = new JsSIP.WebSocketInterface('wss://sip.myhost.com');
Var configuration = {
   Sockets : [ socket ],
   Uri : 'sip:alice@example.com',
   Password : 'superpassword'
};

Var ua = new JsSIP.UA(configuration);
```

> So that's the SDP task solved already? Well, you need SDP for WebRTC anyway, so that must mean yes.

Yes, the SDP task has been resolved.

> I'm happy to sponsor some of this work if you don't have an immediate requirement for it?

I haven't got any sponsors before. If you are willing to sponsor, this will be my first time. :)
Based on my previous experience, I expect it to take around 1~1.5 months.

**Comment by ghenry** [comment]
> > Should `dart-sip-ua` be standalone or should it require flutter-webrtc?
> 
> If `dart-sip-ua` needs to be a client with audio/video, flutter-webrtc is necessary unless you want to use a different media engine, such as your own non-webrtc(For example, a media engine without ice/rtcp-fb.) media engine plugin, you need to wrap the sendOffer/sendAnswer/onOffer/onAnswer series of events and methods into an interface to dock your media engine.
> 

Ah, of course. I forgot about all the native Android (java) and iOS (Objective-C) code in flutter-webrtc.

> > For my use-case I'd want all config to be able to be passed in as I plan to provision it via FCM data.
> 
> If you mean use FCM data to configuration the sip account, audio/video codec order, I think it is possible. Take JsSIP as an example. When creating UA, a configuration parameter will be passed to the constructor.
> 
> ```
> // Create our JsSIP instance and run it:
> 
> Var socket = new JsSIP.WebSocketInterface('wss://sip.myhost.com');
> Var configuration = {
>    Sockets : [ socket ],
>    Uri : 'sip:alice@example.com',
>    Password : 'superpassword'
> };
> 
> Var ua = new JsSIP.UA(configuration);
> ```

Yep, I see that. I've used JsSIP before. Thanks.

> > So that's the SDP task solved already? Well, you need SDP for WebRTC anyway, so that must mean yes.
> 
> Yes, the SDP task has been resolved.

Great.

> > I'm happy to sponsor some of this work if you don't have an immediate requirement for it?
> 
> I haven't got any sponsors before. If you are willing to sponsor, this will be my first time. :)
> Based on my previous experience, I expect it to take around 1~1.5 months.

I've sent you an email to discuss further. I'm busy with other things but will help with this project when I can anyway.

Thanks.

**Comment by joeblew99** [comment]
Hey all,

The pion stack does most of this today i think ?
pion is a webrtc stack.
I regularly use it for session init using TURN and STUN servers.
https://github.com/pion/turn

Or maybe i am missing the intent ?

**Comment by ghenry** [comment]
Thanks. So once you figure out have you can be reached through various
levels of NAT etc, what do you do with that public uri?

Gavin.

**Comment by ghenry** [comment]
https://janus.conf.meetecho.com/siptest.html

This is to achieve something like this. Saving the parties details so you
can call them from another location. How do you do this without sip?
