### ISSUE TITLE
Inform new bugs in mobile client

### ISSUE THREAD

**Issue by palakornv** [flutter-webrtc/flutter-webrtc-demo#30]
I have found a few more issues.
I do the test by using 2 clients, Web-Chrome browser and Android Phone. I found 2 issues from the Android mobile app. 
1. From the Android mobile app, when I click the Video call, the Android app client makes the call to the web client, but the remoted video at the Android and Web client is not showing up
in both Web and Android app.
2. The microphone icon in the Android mobile app is always disabled, and nothing happens when clicking at it. So, I can't enable it.

**Comment by AVancans** [comment]
I also noticed when it's Android initiates an offer to Browser, it exchanges with details and streams, but it's just grey.

[OK] Browser <-> Browser 
[OK] Browser --> Android
[FAIL] Browser <-- Android
