### ISSUE TITLE
Add example for multi-party video calls

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc-demo#5]
Create an example connect to a sfu server.
There may be [mediasoup](https://github.com/versatica/mediasoup), [medooze](https://github.com/medooze/media-server-node), or [pions](https://github.com/pions/webrtc). or other SFU servers. 
If we use nodejs we may need to modify https://github.com/cloudwebrtc/flutter-webrtc-server to work with it.

**Comment by shinewanna** [comment]
Bro,u run with flutter pub or source code?

**Comment by 100cm** [comment]
any progress on this now?
