### ISSUE TITLE
Errors in demo 

### ISSUE THREAD

**Issue by expatsschools** [flutter-webrtc/flutter-webrtc-demo#58]
I am getting few errors 
when i try to run a demo. I am also running https://0.0.0.0:8086/  on local,

Error 1
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _GetUserMediaSampleState#15559(lifecycle state: defunct, not mounted)

Error 2
Note: /Users/bilalrabbi/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/bilalrabbi/Desktop/tools/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning

Error 3
The method 'close' was called on null.
Receiver: null
Tried calling: close()

**Comment by miroslave-ivan** [comment]
I am going to help you with your issues.
I think that it can be solved by entering your ip address or localhost instead 0.0.0.0 in https://0.0.0.0:8086/
thanks
