### ISSUE TITLE
Flutter App Demo server not working 0.0.0.0

### ISSUE THREAD

**Issue by HumbleCarl** [flutter-webrtc/flutter-webrtc-demo#59]
Hello guys. Im trying to connect to the webrtc server with this wss://0.0.0.0:4443 but I can't connect. I tried this wss://demo.cloudwebrtc.com:4443 and it works but the webrtc running on the node can;t connect to the demo app on mobile. can you help me with this one? i'm new with web rtc stuffs

**Comment by LabiadhMo** [comment]
try your local IP Adress
