### ISSUE TITLE
peerConnection can not addStream or createOffer 

### ISSUE THREAD

**Issue by 123zzl321** [flutter-webrtc/flutter-webrtc-demo#60]
the peerConnection that i create is not null. but i get logs below.how to solve this problem,can you help me.
 
E/flutter ( 5051): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exc   eption: PlatformException(peerConnectionAddStreamFailed, peerConnectionAddStream() peerConnection is null, null)
E/flutter ( 5051): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 5051): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 5051): <asynchronous suspension>
E/flutter ( 5051): #2      RTCPeerConnection.addStream (package:flutter_webrtc/rtc_peerconnection.dart:253:20)
E/flutter ( 5051): <asynchronous suspension>
E/flutter ( 5051): #3      RTCSignaling._createPeerConnection (package:zzlrtc/rtc_signaling.dart:251:10)
E/flutter ( 5051): <asynchronous suspension>
E/flutter ( 5051): #4      RTCSignaling.invite (package:zzlrtc/rtc_signaling.dart:316:5)
E/flutter ( 5051): #5      _P2PDemoState._invitePeer (package:zzlrtc/p2p_demo.dart:130:17)
E/flutter ( 5051): <asynchronous suspension>
E/flutter ( 5051): #6      _P2PDemoState._buildRow.<anonymous closure> (package:zzlrtc/p2p_demo.dart:162:17)
E/flutter ( 5051): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
E/flutter ( 5051): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
E/flutter ( 5051): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 5051): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 5051): #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
E/flutter ( 5051): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 5051): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
E/flutter ( 5051): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 5051): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5051): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5051): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5051): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 5051): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5051): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5051): #21     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 5051): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 5051): 
E/flutter ( 5051): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to RTCPeerConnection::createOffer: peerConnection is null
E/flutter ( 5051): #0      RTCPeerConnection.createOffer (package:flutter_webrtc/rtc_peerconnection.dart:230:7)
E/flutter ( 5051): <asynchronous suspension>
E/flutter ( 5051): #1      RTCSignaling._createOffer (package:zzlrtc/rtc_signaling.dart:215:43)
E/flutter ( 5051): <asynchronous suspension>
E/flutter ( 5051): #2      RTCSignaling.invite.<anonymous closure> (package:zzlrtc/rtc_signaling.dart:322:7)
E/flutter ( 5051): #3      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 5051): #4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5051): #5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 5051): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 5051): #7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 5051): #8      Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 5051): #9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 5051): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 5051): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 5051): #12     RTCSignaling._createPeerConnection (package:zzlrtc/rtc_signaling.dart)
E/flutter ( 5051): #13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 5051): #14     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 5051): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5051): #16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 5051): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 5051): #18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 5051): #19     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 5051): #20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 5051): #21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 5051): #22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 5051): #23     createPeerConnection (package:flutter_webrtc/rtc_peerconnection_factory.dart)
E/flutter ( 5051): #24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 5051): #25     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 5051): #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5051): #27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 5051): #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 5051): #29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 5051): #30     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 5051): #31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 5051): #32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter ( 5051): #33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter ( 5051): #34     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter ( 5051): #35     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter ( 5051): #36     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 5051): #37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5051): #38     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 5051): #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 5051): #40     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 5051): #41     Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter ( 5051): #42     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter ( 5051): #43     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 5051): #44     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5051): #45     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5051): #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 5051): #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5051): #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by binghandsom** [comment]
I got the same error,actually struggled for 2 days,nothing processed

**Comment by binghandsom** [comment]
@123zzl321 Have you came through this error.I think this is a bug of fultter_webrtc framework

**Comment by binghandsom** [comment]
@123zzl321 Now I find that when I change the iceServers config as it was this error don‘t occur，so it is very likely due to my setting of iceServers.Hope this can help you.

**Comment by 123zzl321** [comment]
leave your email address i'll send source code  to you

**Comment by 123zzl321** [comment]
@binghandsom
