### ISSUE TITLE
How to perform P2P call sample in flutter-webrtc-demo?

### ISSUE THREAD

**Issue by miroslave-ivan** [flutter-webrtc/flutter-webrtc-demo#62]
Hello guys. Im trying to connect to the webrtc server with this wss://0.0.0.0:4443 but I can't connect.
I entered my local ip address in "Enter Server Address" Modal Window of this demo and then I have got nothing.
can you help me how to solve the problem?
I think that it is the problem changing iceServers array. but I don't know how to edit the iceServer.

**Comment by cloudwebrtc** [comment]
You try the latest demo, which uses a golang server and the only port 8086.
