### ISSUE TITLE
How can I set up server in dot net

### ISSUE THREAD

**Issue by neenabastin123** [flutter-webrtc/flutter-webrtc-demo#65]
Can you please help me with my below doubts?
I am new to flutter and webrtc. I want to set up voip audio call and peer to peer chat in my app. So I could run this sample app successfully. Thank you for this wonderful demo. Since I need to set up the server in dot net, here in your demo app the server url is demo.cloudwebrtc.com. How can I set up the server in C# dot net? What all things I need to do in the server? Can you help me please?

**Comment by shadyshrif** [comment]
Dear @neenabastin123  I checked the code of the server and it is in Go lang. You have to host it a virtual private server VPS and no way to change it to C# and I know
