### ISSUE TITLE
Problem while creating app release with v 0.2.7 and flutter v1.12.13+hotfix.8

### ISSUE THREAD

**Issue by ZatacaSystems** [flutter-webrtc/flutter-webrtc-demo#68]
Hello

I have a problem with version 0.2.7 and flutter version v1.12.13+hotfix.8

I create de apk and when I install it it launches and then closes (crashes)

**Comment by cloudwebrtc** [comment]
Sounds like caused by the latest flutter SDK, I will check it

**Comment by ruepay** [comment]
any update on this issue?
