### ISSUE TITLE
Unable to get audio/Video in P2P Call Sample.

### ISSUE THREAD

**Issue by misteraggressor** [flutter-webrtc/flutter-webrtc-demo#78]
I've setup the server and its working fine. List of connected devices is showing properly in P2P but the the video or other side is not showing, a greyscreen is shwoing instead of caller's video and audio of both sides aren't working as well. Permission is given in android's app setting. Any help would be highly appreciated.

Thanks

**Comment by thedejifab** [comment]
I'm getting this same issue @misteraggressor. have you found a way around this yet @misteraggressor?

**Comment by ycherniavskyi** [comment]
What phone model and Android version are you using?
What type of communication have you tried? Android <-> Android? Browser <-> Android? Browser <-> Browser?

**Comment by jithinbabukmofficial** [comment]
Same issue for me also

**Comment by LabiadhMo** [comment]
same issue !  i tried to use android<-> android

**Comment by phamhuusam** [comment]
I run android emulator ok,
I get source code server run golang with local: http://0.0.0.0:8086
========================================
I setup connect P2P with server: "http://0.0.0.0:8086", but listview but it not show for call.
can you help me?

**Comment by kiaxseventh** [comment]
i have same problem

**Comment by define111** [comment]
I tried to open my own video _localRenderer instead of _remoteRenderer and even this does not work. i use chrome. when I inspect the code with devtools the second video _localRenderer is not being shown, only the first _localRenderer .

**Comment by ganeshub** [comment]
same problem

**Comment by ganeshub** [comment]
@cloudwebrtc
