### ISSUE TITLE
P2P Call can't see video of opposite user. can't install apk on my device its close unfortunately.

### ISSUE THREAD

**Issue by theantiqa** [flutter-webrtc/flutter-webrtc-demo#88]
As you can see i can't see video between 2 mobile device. you can see it in below image.
 
![image](https://user-images.githubusercontent.com/46623939/88478619-84834d00-cf67-11ea-8c2d-84ea70cbddd8.png)

but working well while web to mobile and mobile to web, that you can see in below image.
![image](https://user-images.githubusercontent.com/46623939/88478649-b1376480-cf67-11ea-96d4-aa306042f300.png)

one more thing  I can't install app on my device it can't be open. its unfortunately close whenever i am going to open it. 

Thanks
Tushar

**Comment by ycherniavskyi** [comment]
As for _video of opposite user_ on two simultaneously running emulator - it is more like emulator issue. And in general, it is much better to use real devices for audio/video testing.

As for _app ... can't be open_ on the real device - it looks like ProGuard issue (try to check closed issues with this term).

In any case, it is really hard to provide you any valuable help without any logs and information about your environment.

**Comment by ganeshub** [comment]
"P2P Call can't see video of opposite user"
@theantiqa did you solved the this issue ?

**Comment by mayaparamita** [comment]
> As for _video of opposite user_ on two simultaneously running emulator - it is more like emulator issue. And in general, it is much better to use real devices for audio/video testing.

Hi it happened to me although I used 2 android phones. Anyone knows how to solve this issue?

**Comment by Shanki070** [comment]
check this link:
https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/118#issuecomment-801804745
