### ISSUE TITLE
demo cloudwebRTC server is down

### ISSUE THREAD

**Issue by lumec** [flutter-webrtc/flutter-webrtc-demo#89]
The online demo cloudwebRTC server seems to be down when I try to connect it through the Flutter app or any web browser
link: https://demo.cloudwebrtc.com:8086/

**Comment by OmarHassanT** [comment]
> The online demo cloudwebRTC server seems to be down when I try to connect it through the Flutter app or any web browser
> link: https://demo.cloudwebrtc.com:8086/

this demo sometimes runs and sometimes down, so keep test it everyday.
